In [1]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [4]:
X, y = load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2)
mlp = MLPClassifier(random_state=2)
mlp.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=2, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [5]:
print(mlp.score(X_test, y_test))

0.96


In [7]:
y_pred = mlp.predict(X_test)
incorrect = X_test[y_pred != y_test]
incorrect_true = y_test[y_pred != y_test]
incorrect_pred = y_pred[y_pred != y_test]

j = 0
print(incorrect[j].reshape(8,8).astype(int))
print("true value:", incorrect_true[j])
print("predict value:", incorrect_pred[j])

[[ 0  0 11  7  0  0  0  0]
 [ 0  5 16  3  2 14  3  0]
 [ 0  9 15  0 12 15  0  0]
 [ 0  6 16 15 16  5  0  0]
 [ 0  0  6 15 11  0  0  0]
 [ 0  0  1 16  4  0  0  0]
 [ 0  0  9 12  0  0  0  0]
 [ 0  0 13 10  0  0  0  0]]
true value: 4
predict value: 9
